on unknown command:
	set component unknown command message to text component from "&cCette commande n'existe pas."

on tab complete:
	if event-string contains "/sk" or "/skript":
		player is op
		tab arg-1 is "reload":
			loop tab completions for position 2:
				loop-value does not contain ".git"
				add loop-value to {_tbf::*}
			clear tab completions for position 2
			set tab completions for position 2 to {_tbf::*}
	if event-string contains "/dynsys":
		{rank::%sender's uuid%} is "Admin"
		tab arg-1 is "create":
			set tab completions for position 2 to "hub"
			stop
		else if tab arg-1 is "delete" or "start" or "kill" or "restart":
			set {_svp} to getGlobal("server_list")
			replace all " and " in {_svp} with ", "
			set {_sv::*} to {_svp} split at ", "
			loop {_sv::*}:
				
				loop-value does not contain "dev"
				add loop-value to {_l::*}
			set tab completions for position 2 to {_l::*}
			stop
		else:
			set tab completions for position 1 to "create", "stop", "restart", "kill" and "delete"
			set tab completions for position 2 to "Admin", "Staff", "Donateur" and "Joueur"
			stop
	if event-string contains "/setrank":
		sender is op
		loop {proxy::p_list::*}:
			add loop-value parsed as an offline player to {_l::*}
		set tab completions for position 1 to {_l::*}
		set tab completions for position 2 to "Admin", "Staff", "FDonateur", "Donateur", "FJoueur" and "Joueur"
	if event-string contains "/setrank":
		loop {proxy::p_list::*}:
			loop-value parsed as an offline player is not sender
			add loop-value parsed as an offline player to {_l::*}
		set tab completions for position 1 to {_l::*}

command /help:
	trigger:
		send " "
		send "&6&lLISTE DES COMMANDES"
		send " "
		send "&6Général"
		send "&e/help&f - &oAffiche la liste des commandes."
		send "&e/proxy&f - &oConsulter l'état des serveurs."
		send " "
		send "&6Messages privés"
		send "&e/msg <joueur> <message>&f - &oEnvoie d'un message privé."
		send "&e/r <message>&f - &oRépond directement à la dernière personne qui vous a contacté."
		send "&e/block <joueur>&f - &oPermet de bloquer/débloquer un joueur."
		send " "
		send "&6Social"
		send "&e/friend&f - &oObtenir de l'aide concernant le système d'ami."
		send "&e/party&f - &oObtenir de l'aide concernant le système de groupe."
		